### ISSUE TITLE
Mixlib::ShellOut::InvalidCommandOption: option ':lockdir' is not a valid option for Mixlib::ShellOut

### ISSUE THREAD

**Issue by ramereth** [chef/omnibus#1014]
### Description

It seems #1006 introduced an issue when using the current omnibus-toolchain package (2.0.5) and will not complete builds. If I go back to version 8.1.7 of omnibus, it works correctly.

### Omnibus Version

8.1.8

### Platform Version

Tell us which Operating System distribution, version and architecture the Omnibus build is being executed on.

### Replication Case

```
git clone https://gitlab.com/cinc-project/distribution/auditor.git
cd auditor
docker run -it --rm -v $(pwd):/w -w /w cincproject/omnibus-centos:7
source /home/omnibus/load-omnibus-toolchain.sh
./patch.sh
./build.sh
```

### Build Output

The relevant output of the Omnibus build or a link to a gist of the entire build, if there is one.

Excerpt from build:
```
bundler: failed to load command: omnibus (/builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bin/omnibus)
Mixlib::ShellOut::InvalidCommandOption: option ':lockdir' is not a valid option for Mixlib::ShellOut
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:358:in `block in parse_options'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:312:in `each'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:312:in `parse_options'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:184:in `initialize'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/util.rb:117:in `new'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/util.rb:117:in `shellout'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/util.rb:135:in `shellout!'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:876:in `shellout!'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:415:in `block in appbundle'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:1066:in `instance_eval'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:1066:in `run'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:894:in `block (3 levels) in execute'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:916:in `with_retries'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:893:in `block (2 levels) in execute'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/instrumentation.rb:23:in `measure'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:892:in `block in execute'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:967:in `with_clean_env'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:891:in `execute'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:783:in `block (2 levels) in build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:782:in `each'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:782:in `block in build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/instrumentation.rb:23:in `measure'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/builder.rb:781:in `build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/software.rb:1224:in `execute_build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/software.rb:1102:in `build_me'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/project.rb:1078:in `block (2 levels) in build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/project.rb:1077:in `each'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/project.rb:1077:in `block in build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/licensing.rb:62:in `block in create_incrementally'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/licensing.rb:57:in `tap'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/licensing.rb:57:in `create_incrementally'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/project.rb:1076:in `build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/cli.rb:89:in `build'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/cli/base.rb:33:in `dispatch'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/lib/omnibus/cli.rb:42:in `execute!'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bundler/gems/omnibus-1d97cd9e79a0/bin/omnibus:16:in `<top (required)>'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bin/omnibus:23:in `load'
  /builds/cinc-project/distribution/auditor/bundle/vendor/ruby/2.6.0/bin/omnibus:23:in `<top (required)>'
```

Full build log: https://gitlab.com/cinc-project/distribution/auditor/-/jobs/1220902093#L551

--------------------------------------------------

**Comment by tas50** [comment]
Fixed in https://github.com/chef/omnibus/pull/1016

**Comment by clintoncwolfe** [comment]
This is recurring again - #1019 reintroduced the bad commit.
