### ISSUE TITLE
Issues getting the template/skeleton build working

### ISSUE THREAD

**Issue by bsnape** [chef/omnibus#287]
Hi,

I'm facing a few issues getting the template/skeleton build up and running and wondered if you could offer any insight?

Firstly:

``` bash
$ omnibus -v
Omnibus v3.2.1
```

Which I used to generate my project skeleton:

``` bash
$ omnibus new test
      create  omnibus-test/Gemfile
      create  omnibus-test/.gitignore
      create  omnibus-test/README.md
      create  omnibus-test/omnibus.rb
      create  omnibus-test/config/projects/test.rb
      create  omnibus-test/config/software/c-example.rb
      create  omnibus-test/config/software/erlang-example.rb
      create  omnibus-test/config/software/ruby-example.rb
      create  omnibus-test/.kitchen.local.yml
      create  omnibus-test/.kitchen.yml
      create  omnibus-test/Berksfile
      create  omnibus-test/package-scripts/test/makeselfinst
       chmod  omnibus-test/package-scripts/test/makeselfinst
      create  omnibus-test/package-scripts/test/preinst
       chmod  omnibus-test/package-scripts/test/preinst
      create  omnibus-test/package-scripts/test/prerm
       chmod  omnibus-test/package-scripts/test/prerm
      create  omnibus-test/package-scripts/test/postinst
       chmod  omnibus-test/package-scripts/test/postinst
      create  omnibus-test/package-scripts/test/postrm
       chmod  omnibus-test/package-scripts/test/postrm
      create  omnibus-test/files/mac_pkg/Resources/license.html
      create  omnibus-test/files/mac_pkg/Resources/welcome.html
      create  omnibus-test/files/mac_pkg/Resources/background.png
      create  omnibus-test/files/mac_dmg/Resources/background.png
      create  omnibus-test/files/mac_dmg/Resources/icon.png
      create  omnibus-test/files/windows_msi/Resources/localization-en-us.wxl.erb
      create  omnibus-test/files/windows_msi/Resources/parameters.wxi.erb
      create  omnibus-test/files/windows_msi/Resources/source.wxs
      create  omnibus-test/files/windows_msi/Resources/assets/LICENSE.rtf
      create  omnibus-test/files/windows_msi/Resources/assets/banner_background.bmp
      create  omnibus-test/files/windows_msi/Resources/assets/dialog_background.bmp
      create  omnibus-test/files/windows_msi/Resources/assets/project.ico
      create  omnibus-test/files/windows_msi/Resources/assets/project_16x16.ico
      create  omnibus-test/files/windows_msi/Resources/assets/project_32x32.ico
```

Followed by a local bundle install:

``` bash
$ bundle install --binstubs
Fetching gem metadata from https://rubygems.org/.......
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using addressable (2.3.6)
Using cabin (0.6.1)
Using arr-pm (0.0.9)
Using backports (3.6.0)
Using multipart-post (2.0.0)
Using faraday (0.9.0)
Using berkshelf-api-client (1.2.0)
Using buff-extensions (1.0.0)
Using hashie (2.1.2)
Using varia_model (0.4.0)
Using buff-config (1.0.1)
Using buff-ruby_engine (0.1.0)
Using buff-shell_out (0.1.1)
Using hitimes (1.2.2)
Using timers (4.0.0)
Using celluloid (0.16.0.pre3)
Using nio4r (1.0.0)
Using celluloid-io (0.16.0.pre2)
Using minitar (0.5.4)
Using sawyer (0.5.4)
Using octokit (3.2.0)
Using retryable (1.3.5)
Using buff-ignore (1.1.1)
Using erubis (2.7.0)
Using json (1.8.1)
Using mixlib-log (1.6.0)
Using mixlib-authentication (1.3.0)
Using net-http-persistent (2.9.4)
Using semverse (1.1.0)
Using ridley (4.0.0)
Using dep-selector-libgecode (1.0.2)
Using ffi (1.9.3)
Using dep_selector (1.0.3)
Using solve (1.2.1)
Using thor (0.19.1)
Using berkshelf (3.1.4)
Using chef-sugar (1.3.0)
Using childprocess (0.5.3)
Using clamp (0.6.3)
Using libyajl2 (1.0.1)
Using ffi-yajl (1.0.1)
Using http_parser.rb (0.5.3)
Using ftw (0.0.39)
Using fpm (0.4.42)
Using ipaddress (0.8.0)
Using mixlib-shellout (1.4.0)
Using net-ssh (2.9.1)
Using net-scp (1.2.1)
Using safe_yaml (1.0.3)
Using test-kitchen (1.2.1)
Using kitchen-vagrant (0.15.0)
Using mime-types (1.25.1)
Using mixlib-cli (1.5.0)
Using mixlib-config (2.1.0)
Using systemu (2.6.4)
Using wmi-lite (1.0.0)
Using ohai (7.2.0)
Using uber-s3 (0.2.4)
Using omnibus (3.2.1)
Using bundler (1.5.2)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

So far so good. However, when I try to build the project:

``` bash
$ bin/omnibus build test
                     [BuildVersion] W | Could not extract version information from 'git describe'! Setting version to 0.0.0.
                          [Omnibus] W | Could not load softwares from gem `omnibus-software'. Is it installed?
I could not find a software named `preparation' in any of the sources:

    /Users/bensnape/git/omnibus-test/config/software


/Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:443:in `recursively_load_dependency'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:423:in `block (2 levels) in expand_software'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:422:in `each'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:422:in `block in expand_software'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:421:in `each'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:421:in `expand_software'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:238:in `process_dsl_files'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus.rb:170:in `process_configuration'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli/base.rb:84:in `initialize'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor.rb:355:in `new'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli/base.rb:33:in `dispatch'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli/deprecated.rb:128:in `dispatch'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli.rb:41:in `execute!'
  /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/bin/omnibus:11:in `<top (required)>'
  bin/omnibus:16:in `load'
  bin/omnibus:16:in `<main>'
```

The error references the `omnibus-software` gem the source of which can be found [here](https://github.com/opscode/omnibus-software) but [no gem exists in RubyGems](https://rubygems.org/search?utf8=%E2%9C%93&query=omnibus-software).

It is possible to manually place [preparation.rb](https://github.com/opscode/omnibus-software/blob/master/config/software/preparation.rb) to make the error go away but surely this defeats the purpose of the skeleton/template project?

Furthermore, that error is followed by the missing `version-manifest.rb` file. Again, I can manually add it from [here](https://github.com/opscode/omnibus-software/blob/master/config/software/version-manifest.rb).

I realise that this is because of explicit dependencies in `<project root>/config/projects/<project name>.rb` e.g. in my case `omnibus-test/config/projects/test.rb`:

``` ruby
name 'test'
maintainer 'CHANGE ME'
homepage 'https://CHANGE-ME.com'

install_dir     '/opt/test'
build_version   Omnibus::BuildVersion.semver
build_iteration 1

# creates required build directories
dependency 'preparation'

# test dependencies/components
# dependency 'somedep'

# version manifest file
dependency 'version-manifest'

exclude '\.git*'
exclude 'bundler\/git'
```

Anyway, once I manually added both `preparation.rb` and `version-manifest.rb` I saw the following exception:

``` bash
$ bin/omnibus build ot
                     [BuildVersion] W | Could not extract version information from 'git describe'! Setting version to 0.0.0.
                          [Omnibus] W | Could not load softwares from gem `omnibus-software'. Is it installed?
Building ot 0.0.0+20140731151735...
/Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /var/cache (Errno::EACCES)
    from /Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /Users/bensnape/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/project.rb:957:in `build_me'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli.rb:72:in `build'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli/base.rb:33:in `dispatch'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli/deprecated.rb:128:in `dispatch'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/lib/omnibus/cli.rb:41:in `execute!'
    from /Users/bensnape/.rvm/gems/ruby-2.1.0/gems/omnibus-3.2.1/bin/omnibus:11:in `<top (required)>'
    from bin/omnibus:16:in `load'
    from bin/omnibus:16:in `<main>'
```

And I'm not sure where to go from here!

If it helps, I'm using RVM Ruby `2.1.0` on OSX `10.9.4`:

``` bash
$ rvm use
Using /Users/bensnape/.rvm/gems/ruby-2.1.0
```

I'm familiar with Ruby so I'm happy to help with PR's if we can diagnose the problem.

Thanks,
Ben

**Comment by davidcpell** [comment]
@bsnape sorry to dig up an old issue but I got here from #361 and #471 and am still scratching my head a bit. I realize that ultimately this would be used in CI but is there no OOTB way to "give it a spin" on my local OSX machine to get a feel for how it works??
