### ISSUE TITLE
Could not find a software named `preparation' in any of the sources

### ISSUE THREAD

**Issue by odcinek** [chef/omnibus#361]
Should this be blowing up like that? rvm, ruby-2.0.0-p353, mavericks.

```
# mkdir test1
# cd test1/
# vi Gemfile
# cat Gemfile
source 'https://rubygems.org'
gem 'omnibus'
# bundle install --binstubs
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
(...)
Your bundle is complete!
# ./bin/omnibus new test2
      create  omnibus-test2/Gemfile
      create  omnibus-test2/.gitignore
      create  omnibus-test2/README.md
      create  omnibus-test2/omnibus.rb
      create  omnibus-test2/config/projects/test2.rb
      create  omnibus-test2/config/software/c-example.rb
      create  omnibus-test2/config/software/erlang-example.rb
      create  omnibus-test2/config/software/ruby-example.rb
      create  omnibus-test2/.kitchen.local.yml
      create  omnibus-test2/.kitchen.yml
      create  omnibus-test2/Berksfile
      create  omnibus-test2/package-scripts/test2/makeselfinst
       chmod  omnibus-test2/package-scripts/test2/makeselfinst
      create  omnibus-test2/package-scripts/test2/preinst
       chmod  omnibus-test2/package-scripts/test2/preinst
      create  omnibus-test2/package-scripts/test2/prerm
       chmod  omnibus-test2/package-scripts/test2/prerm
      create  omnibus-test2/package-scripts/test2/postinst
       chmod  omnibus-test2/package-scripts/test2/postinst
      create  omnibus-test2/package-scripts/test2/postrm
       chmod  omnibus-test2/package-scripts/test2/postrm
      create  omnibus-test2/files/mac_pkg/Resources/license.html
      create  omnibus-test2/files/mac_pkg/Resources/welcome.html
      create  omnibus-test2/files/mac_pkg/Resources/background.png
      create  omnibus-test2/files/mac_dmg/Resources/background.png
      create  omnibus-test2/files/mac_dmg/Resources/icon.png
      create  omnibus-test2/files/windows_msi/Resources/localization-en-us.wxl.erb
      create  omnibus-test2/files/windows_msi/Resources/parameters.wxi.erb
      create  omnibus-test2/files/windows_msi/Resources/source.wxs
      create  omnibus-test2/files/windows_msi/Resources/assets/LICENSE.rtf
      create  omnibus-test2/files/windows_msi/Resources/assets/banner_background.bmp
      create  omnibus-test2/files/windows_msi/Resources/assets/dialog_background.bmp
      create  omnibus-test2/files/windows_msi/Resources/assets/project.ico
      create  omnibus-test2/files/windows_msi/Resources/assets/project_16x16.ico
      create  omnibus-test2/files/windows_msi/Resources/assets/project_32x32.ico
# cd omnibus-test2/
# bundle install --binstubs
Fetching gem metadata from https://rubygems.org/.......
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
(...)
Your bundle is complete!
# ./bin/omnibus build test2
                     [BuildVersion] W | Could not extract version information from 'git describe'! Setting version to 0.0.0.
                          [Omnibus] W | Could not load softwares from gem `omnibus-software'. Is it installed?
I could not find a software named `preparation' in any of the sources:

    /private/tmp/test1/omnibus-test2/config/software


/Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:443:in `recursively_load_dependency'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:423:in `block (2 levels) in expand_software'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:422:in `each'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:422:in `block in expand_software'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:421:in `each'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:421:in `expand_software'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:238:in `process_dsl_files'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus.rb:170:in `process_configuration'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus/cli/base.rb:84:in `initialize'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor.rb:355:in `new'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus/cli/base.rb:33:in `dispatch'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus/cli/deprecated.rb:128:in `dispatch'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/lib/omnibus/cli.rb:41:in `execute!'
  /Users/odcinek/.rvm/gems/ruby-2.0.0-p353/gems/omnibus-3.2.2/bin/omnibus:11:in `<top (required)>'
  ./bin/omnibus:16:in `load'
  ./bin/omnibus:16:in `<main>'
```

**Comment by matschaffer** [comment]
I tripped on this too. Seems like the skel should omit the line or the readme or project file should call attention to that you're supposed to do about it.

**Comment by Akshaykapoor** [comment]
`bin/omnibus build test2
                              [CLI] I | Using config from 'omnibus.rb'
                     [BuildVersion] W | Could not extract version information from 'git describe'! Setting version to 0.0.0.
Building test2 0.0.0+20160330010734...
            [Software: preparation] I | Resolving manifest entry for preparation
         [NullFetcher: preparation] I | Fetching `preparation' (nothing to fetch)
       [Software: version-manifest] I | Resolving manifest entry for version-manifest
    [NullFetcher: version-manifest] I | Fetching `version-manifest' (nothing to fetch)
The following shell command exited with status 129:

    $ git -c core.autocrlf=false --git-dir=/var/cache/omnibus/cache/git_cache/opt/test2 --work-tree=/opt/test2 init -q

Output:

    (nothing)

Error:

    Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]


/usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/util.rb:101:in `rescue in shellout!'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/util.rb:97:in `shellout!'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/git_cache.rb:182:in `git_cmd'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/git_cache.rb:67:in `create_cache_path'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/git_cache.rb:130:in `restore'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/software.rb:1006:in `build_me'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/project.rb:1077:in `block in build'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/project.rb:1076:in `each'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/project.rb:1076:in `build'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/cli.rb:83:in `build'
  /usr/local/rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /usr/local/rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/cli/base.rb:33:in `dispatch'
  /usr/local/rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/lib/omnibus/cli.rb:41:in `execute!'
  /usr/local/rvm/gems/ruby-2.1.3/gems/omnibus-5.3.0/bin/omnibus:16:in `<top (required)>'
  bin/omnibus:16:in `load'
  bin/omnibus:16:in `<main>'`

When trying to run the above commands, it fails with following error. Did any of you guys stumble upon this one. I'm using centos6 and rvm, ruby-2.1.3

**Comment by matschaffer** [comment]
@Akshaykapoor  `-c` should be a valid git switch according to https://git-scm.com/docs/git, is your git installation out of date?

**Comment by Akshaykapoor** [comment]
@matschaffer you are right. it could be the case. yum installs git version 1.7.1 (which is way old and doesn't have the -c parameter) on centos 6

```
$ git -c
Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
```

But i'm hoping that should have been mentioned in the requirements for omnibus somewhere. So, i thought a doing a fresh installation (previous dev box had innumerable changes in ruby which i don't even remember) to try omnibus out and still unsuccessful. 

I installed rvm, ruby 2.1.8 on centos6

But this time stumbled upon, 

```
$ omnibus build test2
                              [CLI] I | Using config from 'omnibus.rb'
                     [BuildVersion] W | Could not extract version information from 'git describe'! Setting version to 0.0.0.
           [Software: config_guess] W | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
Building test2 0.0.0+20160330043048...
            [Software: preparation] I | Resolving manifest entry for preparation
         [NullFetcher: preparation] I | Fetching `preparation' (nothing to fetch)
/home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /var/cache/omnibus (Errno::EACCES)
	from /home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
	from /home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
	from /home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
	from /home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
	from /home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `each'
	from /home/cloud-user/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/fetcher.rb:180:in `block in create_required_directories'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/fetcher.rb:179:in `each'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/fetcher.rb:179:in `create_required_directories'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/fetchers/null_fetcher.rb:53:in `fetch'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/software.rb:824:in `fetch'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/thread_pool.rb:64:in `call'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/thread_pool.rb:62:in `loop'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/thread_pool.rb:61:in `catch'
	from /home/cloud-user/.rvm/gems/ruby-2.1.8/gems/omnibus-5.3.0/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```

Is it that root permissions are required when running omnibus ?? (I did a single-user installation of RVM)

And possibly i'll still stumble upon the git issue if this resolves. (But need to confirm after this resolves)

**Comment by Akshaykapoor** [comment]
ah my bad..didn't glance over the README in omnibus.r. It does mention about the usage of root and how to avoid it. 

And as i anticipated, i stumbled on the git issues as before. Will try to update git version and hopefully that should help.
