### ISSUE TITLE
Signed RPM creation fails on CentOS 7

### ISSUE THREAD

**Issue by szechyjs** [chef/omnibus#428]
During the build of the rpm I get thousands of lines of warnings about files listed twice. This breaks the sign-rpm script since it is unexpected output.

snippet from sign-rpm
````ruby
# match the expected prompt exactly, since that's the only way we know if
# something went wrong.
unless prompt == 'Enter pass phrase: '
  STDERR.puts "unexpected output from `#{rpm_cmd}`: '#{prompt}'"
  Process.kill(:KILL, pid)
  exit 1
end
````

output from omnibus
````
                    [Packager::RPM] D | Creating directory `/var/cache/omnibus/pkg'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/BUILD'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/RPMS'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/SRPMS'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/SOURCES'
                    [Packager::RPM] D | Creating directory `/tmp/dms20150210-3935-1pn8rec/SPECS'
                    [Packager::RPM] D | Using vendored resource `filesystem_list'
                    [Packager::RPM] D | Using vendored resource `spec.erb'
                    [Packager::RPM] I | Rendering `/home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/resources/rpm/spec.erb' to `/tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec'
                    [Packager::RPM] I | Signing enabled for .rpm file
                    [Packager::RPM] I | Detected .rpmmacros file at `/home/vagrant'
                    [Packager::RPM] D | Using vendored resource `signing.erb'
                    [Packager::RPM] I | Rendering `/home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/resources/rpm/signing.erb' to `/tmp/d20150210-3935-nh775w/sign-rpm'

                    [Packager::RPM] I | Creating .rpm file
                    [Packager::RPM] D | Removing file `/tmp/d20150210-3935-nh775w/sign-rpm'
                    [Packager::RPM] D | Remove directory `/tmp/d20150210-3935-nh775w'
       STDERR: The following shell command exited with status 1:

           $ HOME=/home/vagrant LC_ALL=C /tmp/d20150210-3935-nh775w/sign-rpm "fakeroot rpmbuild -bb --buildroot /tmp/dms20150210-3935-1pn8rec/BUILD --define '_topdir /tmp/dms20150210-3935-1pn8rec' --sign /tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec"

       Output:

           fakeroot rpmbuild -bb --buildroot /tmp/dms20150210-3935-1pn8rec/BUILD --define '_topdir /tmp/dms20150210-3935-1pn8rec' --sign /tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec

       Error:

           unexpected output from `fakeroot rpmbuild -bb --buildroot /tmp/dms20150210-3935-1pn8rec/BUILD --define '_topdir /tmp/dms20150210-3935-1pn8rec' --sign /tmp/dms20150210-3935-1pn8rec/SPECS/dms-1.3.0+20150210153232.git.21.7ab027d-2.el7.x86_64.rpm.spec`: 'warning: File liste'

       /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/util.rb:101:in `rescue in shellout!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/util.rb:97:in `shellout!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:325:in `block in create_rpm_file'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:370:in `call'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:370:in `with_rpm_signing'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:323:in `create_rpm_file'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/rpm.rb:76:in `block in <class:RPM>'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/base.rb:144:in `instance_eval'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/packagers/base.rb:144:in `run!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:955:in `package_me'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/project.rb:932:in `build_me'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:69:in `build'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli/base.rb:33:in `dispatch'
         /home/vagrant/.gem/ruby/2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/lib/omnibus/cli.rb:41:in `execute!'
         /home/vagrant/.gem/ruby/2.1.2/bundler/gems/omnibus-51ca37c7b299/bin/omnibus:11:in `<top (required)>'
         bin/omnibus:16:in `load'
         bin/omnibus:16:in `<main>'
       ---- End output of bin/omnibus build dms --log-level debug ----
       Ran bin/omnibus build dms --log-level debug returned 1
       [2015-02-10T15:41:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
````

When run without sign-rpm...
````
warning: File listed twice: /opt/dms/bin
warning: File listed twice: /opt/dms/bin/dms-ctl
warning: File listed twice: /opt/dms/bin/dms-ctl
warning: File listed twice: /opt/dms/embedded
warning: File listed twice: /opt/dms/embedded/bin
warning: File listed twice: /opt/dms/embedded/bin
...
...
...
warning: File listed twice: /opt/dms/init
warning: File listed twice: /opt/dms/service
warning: File listed twice: /opt/dms/sv
warning: File listed twice: /opt/dms/version-manifest.txt
warning: Could not canonicalize hostname: default-centos-70.vagrantup.com
Enter pass phrase:
````

**Comment by schisamo** [comment]
@szechyjs We get those same warnings on our builds and the signing works as expected:

```
  [HealthCheck] D | Analyzing dependencies for /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rb-fsevent-0.9.4/spec/rb-fsevent/fsevent_spec.rb
  [HealthCheck] D | Analyzing dependencies for /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rb-fsevent-0.9.4/spec/fixtures/custom
[Packager::RPM] D | Creating directory `/var/cache/omnibus/pkg'
[Packager::RPM] D | Creating directory `/tmp/chefdk20150211-9891-1g420cn/BUILD'
[Packager::RPM] D | Creating directory `/tmp/chefdk20150211-9891-1g420cn/RPMS'
[Packager::RPM] D | Creating directory `/tmp/chefdk20150211-9891-1g420cn/SRPMS'
[Packager::RPM] D | Creating directory `/tmp/chefdk20150211-9891-1g420cn/SOURCES'
[Packager::RPM] D | Creating directory `/tmp/chefdk20150211-9891-1g420cn/SPECS'
[Packager::RPM] D | Using vendored resource `filesystem_list'
[Packager::RPM] D | Using vendored resource `spec.erb'
[Packager::RPM] I | Rendering `/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/el-6/project/chefdk/role/builder/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-51ca37c7b299/resources/rpm/spec.erb' to `/tmp/chefdk20150211-9891-1g420cn/SPECS/chefdk-0.4.0+20150211163949.git.6.758cabf-1.el6.x86_64.rpm.spec'
[Packager::RPM] I | Signing enabled for .rpm file
[Packager::RPM] I | Detected .rpmmacros file at `/home/jenkins'
[Packager::RPM] D | Using vendored resource `signing.erb'
[Packager::RPM] I | Rendering `/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/el-6/project/chefdk/role/builder/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-51ca37c7b299/resources/rpm/signing.erb' to `/tmp/d20150211-9891-si6lt7/sign-rpm'
[Packager::RPM] I | Creating .rpm file
[Packager::RPM] I | Environment:
[Packager::RPM] I |   HOME="/home/jenkins"
[Packager::RPM] I | $ /tmp/d20150211-9891-si6lt7/sign-rpm "fakeroot rpmbuild -bb --buildroot /tmp/chefdk20150211-9891-1g420cn/BUILD --define '_topdir /tmp/chefdk20150211-9891-1g420cn' --sign /tmp/chefdk20150211-9891-1g420cn/SPECS/chefdk-0.4.0+20150211163949.git.6.758cabf-1.el6.x86_64.rpm.spec"
                I | fakeroot rpmbuild -bb --buildroot /tmp/chefdk20150211-9891-1g420cn/BUILD --define '_topdir /tmp/chefdk20150211-9891-1g420cn' --sign /tmp/chefdk20150211-9891-1g420cn/SPECS/chefdk-0.4.0+20150211163949.git.6.758cabf-1.el6.x86_64.rpm.spec
                I | Enter pass phrase: 
                I | 
                I | Pass phrase is good.
                I | Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.MO28iF
                I | Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.kzMRDa
                I | Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.fTyzZF
                I | Processing files: chefdk-0.4.0+20150211163949.git.6.758cabf-1.el6.x86_64
                I | warning: File listed twice: /opt/chefdk/bin
                I | warning: File listed twice: /opt/chefdk/bin/berks
                I | warning: File listed twice: /opt/chefdk/bin/berks
                I | warning: File listed twice: /opt/chefdk/bin/chef
                I | warning: File listed twice: /opt/chefdk/bin/chef
                I | warning: File listed twice: /opt/chefdk/bin/chef-apply
                I | warning: File listed twice: /opt/chefdk/bin/chef-apply
                I | warning: File listed twice: /opt/chefdk/bin/chef-client
                I | warning: File listed twice: /opt/chefdk/bin/chef-client
                I | warning: File listed twice: /opt/chefdk/bin/chef-service-manager
                I | warning: File listed twice: /opt/chefdk/bin/chef-service-manager
                I | warning: File listed twice: /opt/chefdk/bin/chef-shell
                I | warning: File listed twice: /opt/chefdk/bin/chef-shell

<SNIP>

                I | warning: File listed twice: /opt/chefdk/embedded/ssl/misc/c_name
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/misc/tsget
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/misc/tsget
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/misc/tsget
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/misc/tsget
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/openssl.cnf
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/openssl.cnf
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/openssl.cnf
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/private
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/private
                I | warning: File listed twice: /opt/chefdk/embedded/ssl/private
                I | warning: File listed twice: /opt/chefdk/version-manifest.txt
                I | Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/chefdk20150211-9891-1g420cn/BUILD
                I | Generating signature: 1005
                I | Wrote: /tmp/chefdk20150211-9891-1g420cn/RPMS/x86_64/chefdk-0.4.0+20150211163949.git.6.758cabf-1.el6.x86_64.rpm
                I | Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.RSs9Im
[Packager::RPM] D | Removing file `/tmp/d20150211-9891-si6lt7/sign-rpm'
[Packager::RPM] D | Remove directory `/tmp/d20150211-9891-si6lt7'
[Packager::RPM] D | Copying `/tmp/chefdk20150211-9891-1g420cn/RPMS/x86_64/chefdk-0.4.0+20150211163949.git.6.758cabf-1.el6.x86_64.rpm' to `/var/cache/omnibus/pkg'
[Packager::RPM] D | Remove directory `/tmp/chefdk20150211-9891-1g420cn'
   [Compressor] I | No compressor defined for `rhel'.
```

That being said a few questions for you:

* What version of Omnibus are you on? 
* Does your project definition provide a signing_passphrase value (even if it's fake). Here is an example: https://github.com/chef/omnibus-chef/blob/master/config/projects/chef.rb#L70-L72

**Comment by szechyjs** [comment]
- We are running master version from github.
- Our project includes the signing_passphrase

The builds work just fine when building on CentOS 5 & 6. We are only experiencing this problem on CentOS 7.

**Comment by schisamo** [comment]
This still appears to be an issue in our ChefDK builds for EL7:
http://manhattan.ci.chef.co/job/chefdk-build/372/architecture=x86_64,platform=el-7,project=chefdk,role=builder/console

Here is the SPEC file from the above build:
https://gist.githubusercontent.com/schisamo/a1ea5264768aaed13841/raw/chefdk-0.6.0+20150602141332.git.26.2be2593-1.el7.x86_64.rpm.spec
