### ISSUE TITLE
extra_package_file fails when passed a directory

### ISSUE THREAD

**Issue by tomashley** [chef/omnibus#464]
If I pass a directory as an argument to extra_package_file in my project definition:

```
 [Software: version-manifest] I | Dirtied the cache
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1403:in `copy_stream': Is a directory - read (Errno::EISDIR)
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1403:in `block (2 levels) in copy_file'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:in `open'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1593:in `fu_each_src_dest0'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/util.rb:167:in `copy_file'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/packagers/rpm.rb:67:in `block (2 levels) in <class:RPM>'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/packagers/rpm.rb:62:in `each'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/packagers/rpm.rb:62:in `block in <class:RPM>'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/packagers/base.rb:143:in `instance_eval'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/packagers/base.rb:143:in `run!'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/project.rb:955:in `package_me'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/project.rb:932:in `build_me'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/cli.rb:69:in `build'
        from /home/vagrant/.gem/ruby/2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/vagrant/.gem/ruby/2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/vagrant/.gem/ruby/2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/cli/base.rb:33:in `dispatch'
        from /home/vagrant/.gem/ruby/2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/lib/omnibus/cli.rb:41:in `execute!'
        from /home/vagrant/.gem/ruby/2.1.5/gems/omnibus-4.0.0/bin/omnibus:11:in `<top (required)>'
        from bin/omnibus:16:in `load'
        from bin/omnibus:16:in `<main>'
```

My understanding here, and it may be wrong, is that the is the equivalent of passing something akin to below, as you would with fpm.

`--directories /var/log/project`

Is this correct, or does this only work if there are file inside the directory?

**Comment by elafarge** [comment]
+1, I'm encountering the same issue (and there are files in the directory when the error is thrown).

**Comment by elafarge** [comment]
That PR (smallest fix ever :) ) should fix it : https://github.com/elafarge/omnibus/commit/3bb47f4498768252d90615703d29a702118496e0 .
