### ISSUE TITLE
Getting the SSL error when running omnibus build for centos 5.11 and debian squeeze

### ISSUE THREAD

**Issue by pradeepchhetri** [chef/omnibus#531]
I am getting the following error when i am trying to build application for centos:5.11 and debian:squeeze.

```
[NetFetcher: openssl] I | Downloading from `https://www.openssl.org/source/openssl-1.0.1p.tar.gz'
/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
    from /usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
    from /usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
    from /usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
    from /usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
    from /usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/fetchers/net_fetcher.rb:184:in `download'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/fetchers/net_fetcher.rb:82:in `fetch'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/software.rb:634:in `fetch'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/project.rb:996:in `block (3 levels) in download'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/thread_pool.rb:64:in `call'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/thread_pool.rb:62:in `loop'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/thread_pool.rb:61:in `catch'
    from /usr/lib/ruby/gems/2.0.0/bundler/gems/omnibus-e28303ad28a6/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```

I tried updating my `openssl` package and ruby version but didn't get any success. Has anyone seen this issue before.

**Comment by mikemackintosh** [comment]
ditto. when running project build and using ruby or chef as a dependency.

```
...
              [NetFetcher: libtool] I | Downloading from `http://ftp.gnu.org/gnu/libtool/libtool-2.4.tar.gz'
                 [Software: libffi] I | Resolving manifest entry for libffi                                                                                                                                                                                           0% (0 KB/sec)
               [NetFetcher: libffi] I | Downloading from `ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)                                                            0% (0 KB/sec)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
...
```

Stil hacking around open-uri to see if theres a way to fix this up.

**Comment by mikemackintosh** [comment]
i had to manually pull down all the packages and move them to `/var/cache/omnibus/cache`. -- looks like the default OpenSSL ssl_version i'm using is `SSLv23`, which isnt supported by several of the servers i'm pulling from as in (openssl s_client -sslv3 fails)

**Comment by repeatedly** [comment]
Any update on this issue?
I also hit this problem and I want to know how chef developer builds the packages for CentOS 5 / Ubuntu 10.04.

**Comment by repeatedly** [comment]
@ksubrama Could you teach me how to build omnibus package for CentOS 5 / Ubuntu 14.04?

**Comment by schisamo** [comment]
@mikemackintosh @repeatedly Have y'all configured your builders with the [omnibus cookbook](https://github.com/chef-cookbooks/omnibus)? This ensures an old crufty cacert doesn't cause issues on these older platforms. If you use `omnibus new <PROJECT_NAME>` to generate your omnibus project then a `.kitchen.yml` is dropped off which configures everything using said cookbook (the matrix should also include EL5 and Ubuntu 10.04).

**Comment by mikemackintosh** [comment]
How do you configure the cacert.pem for use with an OS X kitchen image? Do you splice it in during the packer steps, or do you runtime it with a fixture within kitchen?

**Comment by repeatedly** [comment]
@schisamo Yes. I try to build my td-agent package with latest kitchen.yml and centos-5.11 box but it got SSL error. Here is the log.

```
[..snip..]
              [NetFetcher: libedit] I | Verifying checksum
                [Software: libyaml] I | Resolving manifest entry for libyaml
              [NetFetcher: libyaml] I | Downloading from `http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz'
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `connect'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:704:in `open'
        from /opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/open-uri.rb:34:in `open'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/fetchers/net_fetcher.rb:189:in `download'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/fetchers/net_fetcher.rb:85:in `fetch'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/software.rb:743:in `fetch'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/project.rb:996:in `block (3 levels) in download'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/thread_pool.rb:64:in `call'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/thread_pool.rb:62:in `loop'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/thread_pool.rb:61:in `catch'
        from /home/vagrant/omnibus-td-agent/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-5724854668f9/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
[vagrant@default-centos-511 omnibus-td-agent]$ 
```

**Comment by repeatedly** [comment]
The problem is CentOS 5's OpenSSL and cert.pem are outdated.

1. Install latest OpenSSL 1.0.1
2. Build ruby with 1. OpenSSL
3. Download cert.pem and add 1024bit CA to it.
4. Replace old cert.pem with 3. cert.pem

On my environment, this step resolves the problem.
I'm not sure why your build doesn't hit this problem.

**Comment by lamont-granquist** [comment]
Closing this issue as an old issue.  The issue may be some combination of:

* Already fixed in new versions.
* Not enough reproduction steps.
* Not clear that the behavior is a bug.
* Insufficient interest in the bug/feature/use-case after an extended period of time.
* Acceptable workarounds exist (or the workarounds are more correct).
* A help request rather than a bug report or feature request.

If this issue was a valid bug or feature request it may not rise to the level of importance were we will consider allocating resources to complete the request.  The impact of fixing it may be small or trivial, while the effort required may be better spent on other issues with higher severity.  It may still be acceptable to open a PR to submit the work, but closing the issue is a statement that we are not accepting the task of doing the work.
