### ISSUE TITLE
Only warn when license_file for the project is missing

### ISSUE THREAD

**Issue by sersut** [chef/omnibus#660]
When the `license_file` pointed to by the project does not exist, omnibus build should not fail. It should only log a warning message.

We ran into this recently in chef and chefdk builds.

```
                        [Licensing] W | Software 'config_guess' uses license 'GPL-3.0 (with exception)' which is not one of the standard licenses identified in https://opensource.org/licenses/alphabetical. Consider using one of the standard licenses.
                        [Licensing] W | License file '/var/cache/omnibus/src/rubygems/LICENSE.txt' does not exist for software 'rubygems'.
                        [Licensing] W | License file '/var/cache/omnibus/src/pry/LICENSE' does not exist for software 'pry'.
/usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-cdd633075fb6/lib/omnibus/licensing.rb:179:in `read': No such file or directory @ rb_sysopen - /usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/LICENSE (Errno::ENOENT)
	from /usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-cdd633075fb6/lib/omnibus/licensing.rb:179:in `project_license_content'
	from /usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-cdd633075fb6/lib/omnibus/licensing.rb:129:in `block in create_project_license_file'
	from /usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-cdd633075fb6/lib/omnibus/licensing.rb:126:in `open'
	from /usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-cdd633075fb6/lib/omnibus/licensing.rb:126:in `create_project_license_file'
	from /usr/home/jenkins/workspace/chef-build/architecture/x86_64/platform/freebsd-10/project/chef/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-cdd633075fb6/lib/omnibus/licensing.rb:60:in `create!'
```

**Comment by sersut** [comment]
We have decided to `Won't Fix` this. See the discussion in the linked PR.
