### ISSUE TITLE
Failed to build on Linux Mint

### ISSUE THREAD

**Issue by seasonxuan** [chef/omnibus#693]
### Description

Failed to build on Linux Mint
### Omnibus Version

rvm 1.27.0 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
Omnibus v5.4.0
### Platform Version

Linux Mint 18 Sarah,Cinnamon x64
### Replication Case

my project name is `demo`
when execute

```
./bin/omnibus build demo -l internal
```

then show error

```
                              [CLI] I | Using config from 'omnibus.rb'
                          [Project] I | Loading project `demo' from `/home/zixuan/Project/omnibus-demo/config/projects/demo.rb'.
                     [BuildVersion] I | $ git describe --tags
                                    I | fatal: Not a git repository (or any parent up to mount point /home)
                                    I | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
                     [BuildVersion] W | Could not extract version information from 'git describe'! Setting version to 0.0.0.
Building demo 0.0.0+20160710024813...
                    [Project: demo] I | Building version manifest
                    [GitRepository] I | $ git rev-parse HEAD
                                    I | fatal: Not a git repository (or any parent up to mount point /home)
                                    I | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
                        [Licensing] W | Project 'demo' does not contain licensing information.
pedump not found - windows health checks disabled
                      [HealthCheck] I | Running health on demo
                      [HealthCheck] I | $ find ./target/ -type f -regextype posix-extended ! -regex '.*(\.[ch]|\.e*rb|\.gemspec|\.gitignore|\.h*h|\.java|\.js|\.json|\.lock|\.log|\.lua|\.md|\.mkd|\.out|\.pl|\.pm|\.png|\.py[oc]*|\.r*html|\.rdoc|\.ri|\.sh|\.sql|\.toml|\.ttf|\.txt|\.xml|\.yml|Gemfile|LICENSE|README|Rakefile|VERSION)$|.*\/share\/doc\/.*|.*\/share\/postgresql\/.*|.*\/share\/terminfo\/.*|.*\/terminfo\/.*' | xargs ldd
                                    I | ldd: missing file arguments
                                    I | Try `ldd --help' for more information.
                    [Packager::DEB] D | Creating directory `./local/pkg'
                    [Packager::DEB] D | Creating directory `/tmp/demo20160710-4176-2gfiy7/DEBIAN'
                    [Packager::DEB] D | Using vendored resource `control.erb'
                    [Packager::DEB] I | $ dpkg --print-architecture
                                    I | amd64
                    [Packager::DEB] I | Rendering `/home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/resources/deb/control.erb' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN/control'
                    [Packager::DEB] D | Adding script `preinst' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN' from /home/zixuan/Project/omnibus-demo/package-scripts/demo/preinst
                    [Packager::DEB] D | Copying `/home/zixuan/Project/omnibus-demo/package-scripts/demo/preinst' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN'
                    [Packager::DEB] D | SCRIPT FILE:  /tmp/demo20160710-4176-2gfiy7/DEBIAN/preinst
                    [Packager::DEB] D | Adding script `postinst' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN' from /home/zixuan/Project/omnibus-demo/package-scripts/demo/postinst
                    [Packager::DEB] D | Copying `/home/zixuan/Project/omnibus-demo/package-scripts/demo/postinst' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN'
                    [Packager::DEB] D | SCRIPT FILE:  /tmp/demo20160710-4176-2gfiy7/DEBIAN/postinst
                    [Packager::DEB] D | Adding script `prerm' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN' from /home/zixuan/Project/omnibus-demo/package-scripts/demo/prerm
                    [Packager::DEB] D | Copying `/home/zixuan/Project/omnibus-demo/package-scripts/demo/prerm' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN'
                    [Packager::DEB] D | SCRIPT FILE:  /tmp/demo20160710-4176-2gfiy7/DEBIAN/prerm
                    [Packager::DEB] D | Adding script `postrm' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN' from /home/zixuan/Project/omnibus-demo/package-scripts/demo/postrm
                    [Packager::DEB] D | Copying `/home/zixuan/Project/omnibus-demo/package-scripts/demo/postrm' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN'
                    [Packager::DEB] D | SCRIPT FILE:  /tmp/demo20160710-4176-2gfiy7/DEBIAN/postrm
                    [Packager::DEB] D | Using vendored resource `md5sums.erb'
                    [Packager::DEB] I | Rendering `/home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/resources/deb/md5sums.erb' to `/tmp/demo20160710-4176-2gfiy7/DEBIAN/md5sums'
                    [Packager::DEB] I | Creating .deb file
                    [Packager::DEB] I | $ fakeroot dpkg-deb -z9 -Zgzip -D --build /tmp/demo20160710-4176-2gfiy7 demo_0.0.0+20160710024813-1_amd64.deb
                                    I | dpkg-deb: building package 'demo' in 'demo_0.0.0+20160710024813-1_amd64.deb'.
Unknown platform `linuxmint'!
I do not know how to proceed!"


/home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/metadata.rb:221:in `truncate_platform_version'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/metadata.rb:137:in `platform_version'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/metadata.rb:55:in `generate'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/packagers/base.rb:148:in `run!'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/project.rb:1134:in `package_me'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/project.rb:1084:in `build'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/cli.rb:84:in `build'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/cli/base.rb:33:in `dispatch'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/lib/omnibus/cli.rb:42:in `execute!'
  /home/zixuan/.rvm/gems/ruby-2.2.4/gems/omnibus-5.4.0/bin/omnibus:16:in `<top (required)>'
  ./bin/omnibus:17:in `load'
  ./bin/omnibus:17:in `<main>'
```

```
tree .
.
├── Berksfile
├── bin
│   ├── aws.rb
│   ├── berks
│   ├── bundler
│   ├── erubis
│   ├── ffi-yajl-bench
│   ├── httpclient
│   ├── kitchen
│   ├── minitar
│   ├── ohai
│   ├── omnibus
│   ├── safe_yaml
│   └── thor
├── config
│   ├── projects
│   │   └── demo.rb
│   └── software
│       └── demo-zlib.rb
├── Gemfile
├── Gemfile.lock
├── local
│   └── pkg
│       ├── demo_0.0.0+20160710023839-1_amd64.deb
│       └── demo_0.0.0+20160710024813-1_amd64.deb
├── omnibus.rb
├── package-scripts
│   └── demo
│       ├── postinst
│       ├── postrm
│       ├── preinst
│       └── prerm
├── pkg
├── README.md
└── target
    ├── LICENSE
    ├── LICENSES
    ├── version-manifest.json
    └── version-manifest.txt
```
### Build Output

see Replication Case above

---

/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by srenatus** [comment]
@seasonxuan Thanks for reporting this! Sorry no one got back to you. Also, I don't think we're targeting Mint... however, it might be easy to make omnibus recognize Mint as Debian-ish? If this is still an issue for you, feel free to submit a PR. Let me know if you need further pointers 😉

**Comment by lamont-granquist** [comment]
closing this as its fairly ancient.
