### ISSUE TITLE
OpenSSL patch error when trying to package a Gem project

### ISSUE THREAD

**Issue by petems** [chef/omnibus#730]
### Description

When trying to run an omnibus run on a gem based project with Ruby, it fails at the openssl step, saying it cant find the patch file.

### Omnibus Version

```
./bin/omnibus --version
Omnibus v5.4.0
```

```ruby
source 'https://rubygems.org'

# Use Berkshelf for resolving cookbook dependencies
gem 'berkshelf', '~> 4.0'

# Install omnibus software
#gem 'omnibus', '~> 3.2'
gem 'omnibus', github: 'opscode/omnibus'

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
gem 'omnibus-software', github: 'opscode/omnibus-software'

# Use Test Kitchen with Vagrant for converging the build environment
gem 'test-kitchen',    '~> 1.2'
gem 'kitchen-vagrant', '~> 0.14'
gem 'facter', '~> 2.2'
```

### Platform Version

```
$ arch
x86_64
$  uname -r -v -p
3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

### Replication Case

```
git clone https://github.com/Misenko/omnibus-oneacct-export
cd omnibus-oneacct-export
bundle install --binstubs
bin/omnibus build oneacct-export
```

### Build Output

```
bin/omnibus build oneacct-export
                    [CLI] I | 2016-10-26T20:33:20+00:00 | Using config from 'omnibus.rb'
 [Software: config_guess] W | 2016-10-26T20:33:20+00:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
Building oneacct-export 0.4.2+20161026203320...
  [Software: preparation] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for preparation
[NullFetcher: preparation] I | 2016-10-26T20:33:20+00:00 | Fetching `preparation' (nothing to fetch)
         [Software: zlib] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for zlib
      [Software: cacerts] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for cacerts
       [Software: xproto] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for xproto
  [Software: util-macros] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for util-macros
 [Software: config_guess] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for config_guess
 [Software: config_guess] W | 2016-10-26T20:33:20+00:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
 [Software: config_guess] W | 2016-10-26T20:33:20+00:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
[Software: pkg-config-lite] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for pkg-config-lite
   [Software: makedepend] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for makedepend
      [Software: openssl] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for openssl
      [Software: libtool] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for libtool
       [Software: libffi] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for libffi
      [Software: libyaml] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for libyaml
     [Software: libiconv] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for libiconv
         [Software: ruby] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for ruby
     [Software: rubygems] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for rubygems
      [Software: liblzma] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for liblzma
[Software: oneacct-export] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for oneacct-export
[NullFetcher: oneacct-export] I | 2016-10-26T20:33:20+00:00 | Fetching `oneacct-export' (nothing to fetch)
[Software: version-manifest] I | 2016-10-26T20:33:20+00:00 | Resolving manifest entry for version-manifest
[NullFetcher: version-manifest] I | 2016-10-26T20:33:20+00:00 | Fetching `version-manifest' (nothing to fetch)
  [Software: preparation] I | 2016-10-26T20:33:21+00:00 | Restored from cache
         [Software: zlib] I | 2016-10-26T20:33:21+00:00 | Restored from cache
      [Software: cacerts] I | 2016-10-26T20:33:21+00:00 | Restored from cache
       [Software: xproto] I | 2016-10-26T20:33:21+00:00 | Restored from cache
  [Software: util-macros] I | 2016-10-26T20:33:21+00:00 | Restored from cache
 [Software: config_guess] W | 2016-10-26T20:33:21+00:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
 [Software: config_guess] W | 2016-10-26T20:33:21+00:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
 [Software: config_guess] I | 2016-10-26T20:33:21+00:00 | Restored from cache
[Software: pkg-config-lite] I | 2016-10-26T20:33:21+00:00 | Restored from cache
   [Software: makedepend] I | 2016-10-26T20:33:21+00:00 | Restored from cache
      [Software: openssl] I | 2016-10-26T20:33:21+00:00 | Could not restore from cache
    [NetFetcher: openssl] I | 2016-10-26T20:33:21+00:00 | Cleaning project directory `/var/cache/omnibus/src/openssl'
    [NetFetcher: openssl] I | 2016-10-26T20:33:21+00:00 | Extracting `/var/cache/omnibus/cache/openssl-1.0.1s.tar.gz' to `/var/cache/omnibus/src/openssl'
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 | Starting build
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 | Environment:
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   CFLAGS="-I/opt/oneacct-export/embedded/include -O2"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   CPPFLAGS="-I/opt/oneacct-export/embedded/include -O2"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   CXXFLAGS="-I/opt/oneacct-export/embedded/include -O2"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   LDFLAGS="-Wl,-rpath,/opt/oneacct-export/embedded/lib -L/opt/oneacct-export/embedded/lib"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   LD_RUN_PATH="/opt/oneacct-export/embedded/lib"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   PATH="/opt/oneacct-export/bin:/opt/oneacct-export/embedded/bin:/usr/lib64/ruby/gems/2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.local/bin:/root/bin"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 |   PKG_CONFIG_PATH="/opt/oneacct-export/embedded/lib/pkgconfig"
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 | $ patch -p1 -i /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-software-02b070d484a1/config/patches/openssl/openssl-1.0.1f-do-not-build-docs.patch
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 | Apply patch `openssl-1.0.1f-do-not-build-docs.patch': 0.0067s
       [Builder: openssl] I | 2016-10-26T20:33:21+00:00 | Build openssl: 0.0074s
/usr/lib64/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338:in `exec': No such file or directory - patch (Errno::ENOENT)
	from /usr/lib64/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338:in `block in fork_subprocess'
	from /usr/lib64/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork'
	from /usr/lib64/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
	from /usr/lib64/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:93:in `run_command'
	from /usr/lib64/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:259:in `run_command'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/util.rb:81:in `shellout'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/util.rb:97:in `shellout!'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:825:in `shellout!'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:240:in `block in patch'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:1012:in `instance_eval'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:1012:in `run'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:843:in `block (3 levels) in execute'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:865:in `with_retries'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:842:in `block (2 levels) in execute'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/instrumentation.rb:23:in `measure'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:841:in `block in execute'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:915:in `with_clean_env'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:840:in `execute'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:704:in `block (2 levels) in build'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:703:in `each'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:703:in `block in build'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/instrumentation.rb:23:in `measure'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/builder.rb:702:in `build'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/software.rb:1161:in `execute_build'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/software.rb:1029:in `build_me'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/project.rb:1077:in `block in build'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/project.rb:1076:in `each'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/project.rb:1076:in `build'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/cli.rb:84:in `build'
	from /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/cli/base.rb:33:in `dispatch'
	from /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/lib/omnibus/cli.rb:42:in `execute!'
	from /usr/lib64/ruby/gems/2.3.0/bundler/gems/omnibus-e2b6cfa81327/bin/omnibus:16:in `<top (required)>'
	from bin/omnibus:17:in `load'
	from bin/omnibus:17:in `<main>'
```

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by petems** [comment]
Ok, I think it might be as simple as patch is not installed...

**Comment by petems** [comment]
Yep, `yum install patch` fixed it. Maybe this'll help some future googler? Closing 😄
