### ISSUE TITLE
Illformed requirement error from bundler when trying to build on windows

### ISSUE THREAD

**Issue by brentm5** [chef/omnibus#756]
### Description

Getting the following error when trying to build on windows

```
       STDERR: C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:101:in `parse': Illformed requirement ["Bundler version 1.14.4"] (Gem::Requirement::BadRequirementError)
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `block in initialize'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `map!'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `initialize'
       	from C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/postit_trampoline.rb:8:in `new'
       	from C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/postit_trampoline.rb:8:in `<top (required)>'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/exe/bundle:10:in `<top (required)>'
       	from C:/languages/ruby/2.3.0/bin/bundle:23:in `load'
       	from C:/languages/ruby/2.3.0/bin/bundle:23:in `<main>'
       Ran call \Users\vagrant\load-omnibus-toolchain.bat && bundle install --without development --deployment returned 1
```

### Omnibus Version

Essentially what is on ksubrama/gcc_investigate (Commit sha below)
61b50f5a20f0930ee977e54cabaff8fe02d3b731

### Platform Version

The actual code is here:

https://github.com/cvent/workup/tree/master/omnibus

But we are trying to build on windows 2016 More specifically `mwrock/Windows2016`

### Replication Case

Just try and build

### Build Output

```
       ---- Begin output of call \Users\vagrant\load-omnibus-toolchain.bat && bundle install --without development --deployment ----
       STDOUT: ========================================
       = Environment
       ========================================

       ALLUSERSPROFILE=C:\ProgramData
       APPDATA=C:\Users\vagrant\AppData\Roaming
       CommonProgramFiles=C:\Program Files\Common Files
       CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
       CommonProgramW6432=C:\Program Files\Common Files
       COMPUTERNAME=WIN-HMM6PQL2DJT
       ComSpec=C:\Windows\system32\cmd.exe
       HOME=C:/Users/vagrant
       HOMEDRIVE=C:
       HOMEPATH=/Users/vagrant
       LOCALAPPDATA=C:\Users\vagrant\AppData\Local
       MSYSTEM=MINGW32
       NUMBER_OF_PROCESSORS=2
       OS=Windows_NT
       Path=C:\msys2\bin;C:\msys2\mingw32\bin;C:\msys2\usr\bin;C:\Program Files (x86)\Git\Cmd;C:\Program Files (x86)\Git\libexec\git-core;C:\languages\ruby\2.3.0\bin;C:\wix;C:\Program Files\7-zip;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\wix;C:\Program Files (x86)\Git\Cmd;C:\Program Files (x86)\Git\libexec\git-core;C:\Program Files\7-zip;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin\
       PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
       PROCESSOR_ARCHITECTURE=AMD64
       PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 70 Stepping 1, GenuineIntel
       PROCESSOR_LEVEL=6
       PROCESSOR_REVISION=4601
       ProgramData=C:\ProgramData
       ProgramFiles=C:\Program Files
       ProgramFiles(x86)=C:\Program Files (x86)
       ProgramW6432=C:\Program Files
       PROMPT=$P$G
       PSModulePath=C:\Users\vagrant\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
       PUBLIC=C:\Users\Public
       SSL_CERT_FILE=C:\languages\ruby\2.3.0\ssl\certs\cacert.pem
       SystemDrive=C:
       SystemRoot=C:\Windows
       TEMP=C:\Users\vagrant\AppData\Local\Temp
       TEST_KITCHEN=1
       TMP=C:\Users\vagrant\AppData\Local\Temp
       USER=vagrant
       USERDOMAIN=WIN-HMM6PQL2DJT
       USERNAME=vagrant
       USERPROFILE=C:\Users\vagrant
       windir=C:\Windows


       LC_ALL=en_US.UTF-8
       LANGUAGE=en_US.UTF-8
       LANG=en_US.UTF-8


       ========================================
       = Tool Versions
       ========================================

       7-Zip..........7-Zip [64] 15.14 : Copyright (c) 1999-2015 Igor Pavlov : 2015-12-31
       Bundler........Bundler version 1.14.4
       GCC............gcc (Rev1, Built by MSYS2 project) 6.3.0
       Git............git version 2.6.2.windows.1
       Make...........GNU Make 4.2.1
       Ruby...........ruby 2.3.0p0 (2015-12-25 revision 53290) [i386-mingw32]
       RubyGems.......2.5.1
       WiX:Candle.....Windows Installer XML Toolset Compiler version 3.10.2.2516
       WiX:Heat.......Windows Installer XML Toolset Toolset Harvester version 3.10.2.2516
       WiX:Light......Windows Installer XML Toolset Linker version 3.10.2.2516

       ========================================
       STDERR: C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:101:in `parse': Illformed requirement ["Bundler version 1.14.4"] (Gem::Requirement::BadRequirementError)
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `block in initialize'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `map!'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `initialize'
       	from C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/postit_trampoline.rb:8:in `new'
       	from C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/postit_trampoline.rb:8:in `<top (required)>'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from C:/languages/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/exe/bundle:10:in `<top (required)>'
       	from C:/languages/ruby/2.3.0/bin/bundle:23:in `load'
       	from C:/languages/ruby/2.3.0/bin/bundle:23:in `<main>'
       ---- End output of call \Users\vagrant\load-omnibus-toolchain.bat && bundle install --without development --deployment ----
       Ran call \Users\vagrant\load-omnibus-toolchain.bat && bundle install --without development --deployment returned 1
```

**Comment by tduffield** [comment]
I'm not sure we've tested on Server 2016. @schisamo or @rhass are we building on that anywhere in our pipeline?

**Comment by schisamo** [comment]
The fact that the stack trace comes from the languages cookbook makes me think @brentm5 isn't using the latest version of the [omnibus cookbook](https://github.com/chef-cookbooks/omnibus) which installs the new Window's omnibus-toolchain.

**Comment by brentm5** [comment]
Let me go ahead and try that on master of the omnibus cookbook, I was using the `ksubrama/gcc_investigate` branch of omnibus (not 100% sure why that was the case)

**Comment by brentm5** [comment]
Ok so tried again, using the master branch of Omnibus and version 5.1.3 of the omnibus cookbook and the only difference is I get a different version of bundler:

```
 ========================================
       = Tool Versions
       ========================================

       7-Zip..........7-Zip [64] 15.14 : Copyright (c) 1999-2015 Igor Pavlov : 2015-12-31
       Bundler........Bundler version 1.14.3
       GCC............gcc (Rev1, Built by MSYS2 project) 6.3.0
       Git............git version 2.10.2.windows.1
       Make...........GNU Make 4.2.1
       Ruby...........ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
       RubyGems.......2.6.10
       WiX:Candle.....Windows Installer XML Toolset Compiler version 3.10.2.2516
       WiX:Heat.......Windows Installer XML Toolset Toolset Harvester version 3.10.2.2516
       WiX:Light......Windows Installer XML Toolset Linker version 3.10.2.2516

       ========================================
       STDERR: C:/opscode/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:101:in `parse': Illformed requirement ["Bundler version 1.14.3"] (Gem::Requirement::BadRequirementError)
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:131:in `block in initialize'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:131:in `map!'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:131:in `initialize'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/postit_trampoline.rb:8:in `new'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/postit_trampoline.rb:8:in `<top (required)>'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:10:in `<top (required)>'
       	from C:/opscode/omnibus-toolchain/embedded/bin/bundle:22:in `load'
       	from C:/opscode/omnibus-toolchain/embedded/bin/bundle:22:in `<main>'
       ---- End output of call \Users\vagrant\load-omnibus-toolchain.bat && bundle install --without development --path vendor/bundle ----
       Ran call \Users\vagrant\load-omnibus-toolchain.bat && bundle install --without development --path vendor/bundle returned 1
```

It installed the version 1.1.52-1-x86 of the omnibus-toolchain as well

**Comment by schisamo** [comment]
@brentm5 You don't need a special branch of Omnibus any longer, please move your project to `master` (ditto on omnibus-software).

**Comment by brentm5** [comment]
@schisamo Just tried that and still get the same error.  Maybe it is just an issue with windows 2016?

**Comment by rhass** [comment]
@tduffield We currently do not build or test on 2016 yet. However, yesterday we started publishing appx packages for angrychef and angry-omnibus-toolchain which we build on 2012R2 and should work fine on 2016, however it not official tested just yet.

@brentm5 The branches which I am developing off of until we can land everything in master are:
```
gem "omnibus", github: "chef/omnibus", branch: "tduffield/omnibus-toolchain"
gem "omnibus-software", github: "chef/omnibus-software", branch: "windows_toolchain/rhass/chefdk"
```
Assuming you use the latest version of the omnibus cookbook with a fresh system (unfortunately you need to rebuild the box to ensure correct state) You should be able to build on 2016, however to avoid some confusion I suggest pinning `1.1.46` of the `omnbius-toolchain` until everything lands in the master branches.

**Comment by rhass** [comment]
@brentm5 This is an example of the omnbus branch pinnings for the angrychef build I am currently working on: https://github.com/chef/chef/blob/windows_toolchain/omnibus/Gemfile

**Comment by rhass** [comment]
This should be resolved once #759 is merged and we have a new version of [chef/omnibus-toolchain](https://github.com/chef/omnibus-toolchain) released. The latter of the two could take a week or two since there is some internal work against our CI infrastructure which needs to be done to make this happen.

**Comment by brentm5** [comment]
Thanks @rhass Ill try looking more into it when a new version is released in a week or so.

**Comment by lamont-granquist** [comment]
```
C:/languages/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/postit_trampoline.rb
```

this is coming from the bundler 1.14.4 trampolining code

```
["Bundler version 1.14.4"] (Gem::Requirement::BadRequirementError)
```

this string is from the BUNDLE_VERSION environment variable that gets set in appveyor.

this isn't a bug in omnibus.

we also don't support bundler 1.14.x for chef-12 and likely never will.

i'll look at the appveyor and travis configs in chef/chef and see if there's something that needs to be done there to avoid bundler 1.14.x

**Comment by lamont-granquist** [comment]
oh yeah i see this is hand built on windows, so yeah, you need to use bundler 1.12.x and remove bundler 1.14.x
