### ISSUE TITLE
ncurses build fails due to git_cache case sensitivity

### ISSUE THREAD

**Issue by curiositycasualty** [chef/omnibus#765]
### Description

Kept having the build die off on me with the below.

A cursory googling revealed that setting `core.ignorecase` to `false` resolves this issue (which setting this in `/var/cache/omnibus/cache/git_cache/opt/thing/config` did-- but I'm opening this issue instead of opening a PR because I'm not sure what the impact is.

### Omnibus Version

master@76d907

### Platform Version

Ubuntu 14.04 via generated .kitchen.yml

### Replication Case

- Generate omnibus project using `new` omnibus subcommand
- Create a project that includes ncurses a dependency
- Setup a test-kitchen builder
- build

### Build Output

```bash
[Builder: ncurses] I | 2017-03-17T23:00:54+00:00 | Finished build
The following shell command exited with status 128:

    $ git -c core.autocrlf=false --git-dir=/var/cache/omnibus/cache/git_cache/opt/thing --work-tree=/opt/thing add -A -f

Output:

    (nothing)

▽
[core]

Error:

    fatal: Will not add file alias 'embedded/share/terminfo/32/2621a' ('embedded/share/terminfo/32/2621A' already exists in index)


/home/vagrant/omnibus/lib/omnibus/util.rb:139:in `rescue in shellout!'
  /home/vagrant/omnibus/lib/omnibus/util.rb:135:in `shellout!'
  /home/vagrant/omnibus/lib/omnibus/git_cache.rb:198:in `git_cmd'
  /home/vagrant/omnibus/lib/omnibus/git_cache.rb:129:in `incremental'
  /home/vagrant/omnibus/lib/omnibus/software.rb:1212:in `execute_build'
  /home/vagrant/omnibus/lib/omnibus/software.rb:1091:in `build_me'
  /home/vagrant/omnibus/lib/omnibus/project.rb:1077:in `block (2 levels) in build'
  /home/vagrant/omnibus/lib/omnibus/project.rb:1076:in `each'
  /home/vagrant/omnibus/lib/omnibus/project.rb:1076:in `block in build'
  /home/vagrant/omnibus/lib/omnibus/licensing.rb:62:in `block in create_incrementally'
  /home/vagrant/omnibus/lib/omnibus/licensing.rb:57:in `tap'
  /home/vagrant/omnibus/lib/omnibus/licensing.rb:57:in `create_incrementally'
  /home/vagrant/omnibus/lib/omnibus/project.rb:1075:in `build'
  /home/vagrant/omnibus/lib/omnibus/cli.rb:84:in `build'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/vagrant/omnibus/lib/omnibus/cli/base.rb:33:in `dispatch'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/vagrant/omnibus/lib/omnibus/cli.rb:42:in `execute!'
  /home/vagrant/omnibus/bin/omnibus:16:in `<top (required)>'
  bin/omnibus:17:in `load'
  bin/omnibus:17:in `<main>'
```

--------------------------------------------------
/cc @chef/omnibus-maintainers

**Comment by schisamo** [comment]
Any thoughts on the impact here @chef/omnibus-maintainers ?

**Comment by curiositycasualty** [comment]
I think the default value for this config rides in on `git init -q`: https://github.com/chef/omnibus/blob/master/lib/omnibus/git_cache.rb#L78

What I'd be most concerned about is whether or not this will dirty peoples' caches or interupt thier workflow in other ways.

**Comment by srenatus** [comment]
@curiositycasualty this is done, right? Thanks for the fix 👍

**Comment by curiositycasualty** [comment]
@srenatus  Yup, all settled up.
