### ISSUE TITLE
Missing config option `publish_s3_profile`

### ISSUE THREAD

**Issue by legal90** [chef/omnibus#791]
### Description

PR #781 has introduced a regression of `omnibus publish` command

### Omnibus Version

v5.6.1 from master branch (d9156f453d661f71e5ee894ee6331769025f44c5)

### Platform Version

OS X 10.12.5,  Ubuntu 14.04 x86_64

### Replication Case

```
bundle exec omnibus publish s3 <bucket_name> <path/to/package.deb>
```
### Build Output

```
[CLI] I | 2017-07-12T13:47:59+02:00 | Using config from 'omnibus.rb'
[Command::Publish] I | 2017-07-12T13:47:59+02:00 | Using config from 'omnibus.rb'
[S3Publisher] I | 2017-07-12T13:47:59+02:00 | Starting S3 publisher
bundler: failed to load command: omnibus (/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bin/omnibus)
NoMethodError: undefined method `publish_s3_profile' for Omnibus::Config:Class
Did you mean?  publish_retries
/Users/username/Workspace/omnibus/lib/omnibus/publishers/s3_publisher.rb:54:in `s3_configuration'
/Users/username/Workspace/omnibus/lib/omnibus/s3_helpers.rb:56:in `client'
/Users/username/Workspace/omnibus/lib/omnibus/s3_helpers.rb:104:in `bucket'
/Users/username/Workspace/omnibus/lib/omnibus/s3_helpers.rb:130:in `store_object'
/Users/username/Workspace/omnibus/lib/omnibus/publishers/s3_publisher.rb:33:in `block in publish'
/Users/username/Workspace/omnibus/lib/omnibus/publishers/s3_publisher.rb:26:in `each'
/Users/username/Workspace/omnibus/lib/omnibus/publishers/s3_publisher.rb:26:in `publish'
/Users/username/Workspace/omnibus/lib/omnibus/publisher.rb:29:in `publish'
/Users/username/Workspace/omnibus/lib/omnibus/cli/publish.rb:101:in `publish'
/Users/username/Workspace/omnibus/lib/omnibus/cli/publish.rb:61:in `s3'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/username/Workspace/omnibus/lib/omnibus/cli/base.rb:33:in `dispatch'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/username/Workspace/omnibus/lib/omnibus/cli/base.rb:33:in `dispatch'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/username/Workspace/omnibus/lib/omnibus/cli.rb:42:in `execute!'
/Users/username/Workspace/omnibus/bin/omnibus:16:in `<top (required)>'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bin/omnibus:22:in `load'
/Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bin/omnibus:22:in `<top (required)>'
```

**Comment by srenatus** [comment]
Thanks for looking into this!

I'm a bit confused, though, your error refers to `publish_dir_pattern`, which isn't a thing yet on master, is it? [That PR hasn't been merged.](https://github.com/chef/omnibus/pull/790)

**Comment by legal90** [comment]
@srenatus Ah, sorry. I've updated the output snippet above. 
Now it's what I get with the clean state of d9156f4
