### ISSUE TITLE
Seeing an error: undefined method `split' 

### ISSUE THREAD

**Issue by vivekKodira** [chef/omnibus#800]
### Description
I'm trying omnibus for the first time and am using the [docker image](https://hub.docker.com/r/opsrock/omnibus_base_ubuntu14/). After building the image, when I try to run it, I see an error. 

### Omnibus Version
5.6
### Platform Version
Docker. Ubuntu 14. https://hub.docker.com/r/opsrock/omnibus_base_ubuntu14/
### Replication Case

My project.rb file:
```
name "somename"
maintainer "vivek"
homepage "https://na.com"

# Defaults to C:/somename on Windows
# and /opt/somename on all other platforms
install_dir "#{default_root}/#{name}"

build_version 1
build_iteration 1

# Creates required build directories
#dependency "preparation"

# somename dependencies/components
# dependency "somedep"

# Version manifest file
#dependency "version-manifest"

exclude "**/.git"
exclude "**/bundler/git"
```

### Build Output
After building the image, when I run it, I see the following error:
```
[2017-09-22T11:52:10+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
/opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/build_version_dsl.rb:135:in `has_timestamp?': undefined method `split' for 1:Fixnum (NoMethodError)
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/build_version_dsl.rb:120:in `maybe_append_timestamp'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/build_version_dsl.rb:111:in `build_version='
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/build_version_dsl.rb:38:in `initialize'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/project.rb:380:in `new'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/project.rb:380:in `build_version'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `public_send'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:130:in `block (3 levels) in cleanroom'
	from /home/omnibus/omnibus-project/config/projects/jfmc.rb:15:in `evaluate'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `instance_eval'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:70:in `evaluate'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:56:in `evaluate_file'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/cleanroom-1.0.0/lib/cleanroom.rb:173:in `evaluate_file'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/project.rb:46:in `load'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/cli.rb:85:in `build'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/cli/base.rb:33:in `dispatch'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/lib/omnibus/cli.rb:42:in `execute!'
	from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.3.0/gems/omnibus-5.6.1/bin/omnibus:16:in `<top (required)>'
	from ./bundle_bin/omnibus:17:in `load'
	from ./bundle_bin/omnibus:17:in `<main>'
```

--------------------------------------------------

**Comment by scotthain** [comment]
Hi @vivekKodira - I'd check to make sure the `append_timestamp` config item is set correctly in your `omnibus.rb` file (It should be true or false).

Also just as an FYI, the Docker image is not something that we at Chef created or support, and looks a bit out of date, from looking at the git repo...

**Comment by vivekKodira** [comment]
Hi @scotthain Thank you for your time. I apologize for creating the ticket here wrongly. Will close it.

**Comment by vivekKodira** [comment]
Also, yes: that was the cause of the issue I reported here. 

Another mistake I've made in the file above is use a number for "build_version". Once I fixed both these issues, I was able to make progress.
