### ISSUE TITLE
Omnibus buil fails with chef-sugar-ng-5.1.8

### ISSUE THREAD

**Issue by akuzminsky** [chef/omnibus#913]
### Description

If `chef-sugar-ng` is not pinned, omnibus installs version `5.1.8`. It breaks the build.

### Omnibus Version

`6.1.9`

### Platform Version

```
# cat /etc/*-release
CentOS Linux release 7.6.1810 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core)
```
### Build Output

```
bin/omnibus build twindb-backup
/usr/local/rvm/gems/ruby-2.6.1/gems/chef-sugar-ng-5.1.8/lib/chef/sugar/architecture.rb:23:in `<module:Architecture>': uninitialized constant Chef::VERSION (NameError)
        from /usr/local/rvm/gems/ruby-2.6.1/gems/chef-sugar-ng-5.1.8/lib/chef/sugar/architecture.rb:19:in `<module:Sugar>'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/chef-sugar-ng-5.1.8/lib/chef/sugar/architecture.rb:18:in `<class:Chef>'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/chef-sugar-ng-5.1.8/lib/chef/sugar/architecture.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/lib/omnibus/sugarable.rb:17:in `require'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/lib/omnibus/sugarable.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/lib/omnibus.rb:24:in `require'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/lib/omnibus.rb:24:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/lib/omnibus/cli.rb:18:in `require'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/lib/omnibus/cli.rb:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/bin/omnibus:10:in `require'
        from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-6.1.9/bin/omnibus:10:in `<top (required)>'
        from bin/omnibus:29:in `load'
        from bin/omnibus:29:in `<main>'
make: *** [package] Error 1
```

However when I add this to `Gemfile`, the build succeeds.
```
gem 'chef-sugar-ng', '~> 5.0.4'
```

**Comment by tas50** [comment]
Thanks for the report. We released 5.1.9, which should clear this all up.
