### ISSUE TITLE
Ruby 2.7 failure in download_helpers

### ISSUE THREAD

**Issue by jkohen** [chef/omnibus#923]
### Description

The hash needs to be expanded. As-is, it is an error with Ruby 2.7.0:

```
lib/omnibus/download_helpers.rb:80: warning: Splitting the last argument into positional and keyword parameters is deprecated
lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
/usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:153:in `open_uri': extra arguments (ArgumentError)
```

I tried to fix this in https://github.com/chef/omnibus/pull/922, but I ran into issues that I don't know how to fix, because I'm not very familiar with Ruby.

The Ruby documentation on the new behavior is comprehensive, but as far as I can see, there is no code that works in both Ruby versions without changing how things are wired: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

### Omnibus Version

6.1.9

### Platform Version

Tell us which Operating System distribution, version and architecture the Omnibus build is being executed on.

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Build Output

The relevant output of the Omnibus build or a link to a gist of the entire build, if there is one.

The verbose build output (`omnibus build <PROJECT> -l internal`) may be useful, but please link to a gist, or truncate it.

--------------------------------------------------

**Comment by mattray** [comment]
Started doing Chef 16 builds with Ruby 2.7.1 and ran into this error, reverting to Ruby 2.6.6 avoids it. Here's a bigger stack-trace.

```
#<Thread:0x000055d56492cea0 /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/thread_pool.rb:57 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	14: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
	13: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/thread_pool.rb:61:in `catch'
	12: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	11: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/thread_pool.rb:62:in `loop'
	10: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	 9: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
	 8: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/software.rb:914:in `fetch'
	 7: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	 6: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/fetchers/net_fetcher.rb:176:in `download'
	 5: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/download_helpers.rb:80:in `download_file!'
	 4: from /home/omnibus/.rbenv/versions/2.7.1/lib/ruby/2.7.0/open-uri.rb:19:in `open'
	 3: from /home/omnibus/.rbenv/versions/2.7.1/lib/ruby/2.7.0/open-uri.rb:50:in `open'
	 2: from /home/omnibus/.rbenv/versions/2.7.1/lib/ruby/2.7.0/open-uri.rb:744:in `open'
	 1: from /home/omnibus/omnibus-toolchain/.bundle/ruby/2.7.0/bundler/gems/omnibus-3327abfbe926/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
/home/omnibus/.rbenv/versions/2.7.1/lib/ruby/2.7.0/open-uri.rb:153:in `open_uri': extra arguments (ArgumentError)
```
